spring:
  ai:
    openai:
      api-key: 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

  datasource:
    url: jdbc:postgresql://dpg-d1jikqemcj7s739t2grg-a.oregon-postgres.render.com/ai_mathteacher_a
    driver-class-name: org.postgresql.Driver
    username: ai_mathteacher_a_user
    password: O6cbLCT40qqMA4WXgp4s3hqSaOhnuOUW

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    jackson:
      serialization:
        fail-on-empty-beans: false

  server:
    port: 8080
