server:
  port: ${BACKEND_WEB_PORT:8080}

spring:
  application:
    name: ai-teacher-a
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ai_math_teacher_a?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:nnnnnn}
