server:
  port: ${PORT:8080}

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:nnnnnn}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_CLIENT_ID:nnnnnn}
            redirect-uri: "http://localhost:8080/oauth/kakao/callback"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
  application:
    name: ai-teacher-a
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_math_teacher_a}
    username: ${DB_ID:postgres}
    password: ${DB_PW:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
cloudflare:
  r2:
    endpoint-url: ${R2_URL}
    region: ${R2_REGION}
    credentials:
      access-key-id: ${R2_ACCESS_ID}
      secret-access-key: ${R2_ACCESS_KEY}
    bucket: ${R2_BUCKET}
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIATX3PIFBILAQLZMPM
      secret-key: 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
    s3:
      bucket: gpt-vision-bucket-test
frontend:
  redirect-uri: http://localhost:3000/login/success