server:
  port: ${BACKEND_WEB_PORT:8080}

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a587e58dfef395c68fe47e99f5844b5c
            redirect-uri: "http://localhost:8080/oauth/kakao/callback"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
  application:
    name: ai-teacher-a
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_math_teacher_a
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:nnnnnn}
